# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUvzhLOHK8r2qPI3o9hgZ-jxLYuHmDU7
"""

import pandas as pd

data={
    "ism":["Oyatulloh","Mahdiya","Ozodbek","Toshpolat","Sarvar"],
    "familiya":["Mamirov","Tohirova","Abdumutalov","Valijonov","Abdumutalov"],
    "manzili":["Andijon,","Namangan","Quvasoy","Toshkent","Shahrihon"],
    "yoshi":[20,17,25,18,28],
    "kursi":[2,1,4,3,5],
    "jinsi":["erkak","ayol","erkak","erkak","erkak"]
}
baza=pd.DataFrame(data)
print(baza)

filter=baza[baza["jinsi"]=="erkak"]
print(filter)

filter=baza[baza["kursi"]>=1]
print(baza)

baza["yoshi"]+=7
print(baza)

baza.to_excel("Ro'yxat.xslx")